version: '2'

services:
  nginx:
    container_name: nginx-lb-skinfosec
    build: ../nginx
    links:
      - app-1:app-1
    ports:
      - 3000:8585
    depends_on:
      - app-1

  app-1:
    container_name: node-skinfosec-1
    image: node-skinfosec:skinfosec
    ports:
      - 3100:3000
    environment:
      KEYVALSTORE: /keyValStore_fabricClientOrg1
      MEMBER_ID: admin
      MEMBER_PWD: adminpw
      CHAINCODE_ID: Certificate
      CHAINCODE_VERSION: v1.2
      CHANNEL_NAME: channel1
      ORDERER_URL: grpcs://10.250.46.165:7050
      ORDERER_SERVER_HOSTNAME: orderer.skinfosec.com
      ORDERER_TLS_CACERTS: server/api/config/infosec/crypto-config/ordererOrganizations/skinfosec.com/orderers/orderer.skinfosec.com/msp/tlscacerts/tlsca.skinfosec.com-cert.pem
      ORGS_ORG1_MSPID: Org1MSP
      ORGS_ORG1_CA_URL: https://10.250.46.165:7054
      ORGS_ORG1_CA_NAME: ca1
      ORGS_ORG1_PEERS_PEER1_REQUESTS: grpcs://10.250.46.165:7051
      ORGS_ORG1_PEERS_PEER1_EVENTS: grpcs://10.250.46.165:7053
      ORGS_ORG1_PEERS_PEER1_SERVER_HOSTNAME: peer0.org1.skinfosec.com
      ORGS_ORG1_PEERS_PEER1_TLS_CA_CERTS: server/api/config/infosec/crypto-config/peerOrganizations/org1.skinfosec.com/peers/peer0.org1.skinfosec.com/msp/tlscacerts/tlsca.org1.skinfosec.com-cert.pem
      ORGS_ORG1_PEERS_PEER2_REQUESTS: grpcs://10.250.46.165:8051
      ORGS_ORG1_PEERS_PEER2_EVENTS: grpcs://10.250.46.165:8053
      ORGS_ORG1_PEERS_PEER2_SERVER_HOSTNAME: peer1.org1.skinfosec.com
      ORGS_ORG1_PEERS_PEER2_TLS_CA_CERTS: server/api/config/infosec/crypto-config/peerOrganizations/org1.skinfosec.com/peers/peer1.org1.skinfosec.com/msp/tlscacerts/tlsca.org1.skinfosec.com-cert.pem
      QUERY_TARGET_PEER: grpcs://10.250.46.165:7051
      LOG_LEVEL: ERROR
